version: '3'

services:
  gatekeeper-db:
    image: docker.io/bitnami/postgresql:11.12.0-debian-10-r44
    environment:
      POSTGRES_DB: gatekeeperdb
      POSTGRES_PASSWORD: mysecretpassword
    expose:
      - "5432"
    ports:
      - "5432:5432"
  rabbitmq:
    image: bitnami/rabbitmq:3.8.9
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: pass
    ports:
      - 5672:5672
      - 15672:15672
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  broker:
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafdrop:
    network_mode: host
    depends_on:
      - zookeeper
      - broker
    image: obsidiandynamics/kafdrop:3.27.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: localhost:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=testing
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: testing
    ports:
      - "5601:5601"
volumes:
  es_data:
    driver: local
